import type { Aura } from "@/data/repository/campaign/Aura";
import type { AuraRepository } from "@/data/repository/campaign/AuraRepository";
import * as _ from "lodash-es";

export class CampaignLogAuraRepository implements AuraRepository {
  private auras: Aura[] = [
    {
      id: "ancient-spell",
      name: "Ancient Spell",
      effect: "At the beginning of your turn, you gain SHIELD 1.",
    },
    {
      id: "bastion",
      name: "Bastion",
      effect: "You can't be TRAMPLED by Vicious Maulers.",
    },
    {
      id: "blessing-of-prosperity",
      name: "Blessing of Prosperity",
      effect: "Whenever you draw a Chest card, draw an additional Chest card and choose one among them to keep.",
    },
    {
      id: "calm-mind",
      name: "Calm Mind",
      effect: "Whenever any Hero receives a CLEANSE effect, they REGAIN 2 HEALTH.",
    },
    {
      id: "city-hero",
      name: "City Hero",
      effect:
        "Whenever you take a Recall Action, make a Wisdom (blue) Skill Challenge of Difficulty 13. Each Wisdom cube you have gives you a +2 bonus to your roll. If you Succeed, avoid the Curse Cube Penalty you would take. Otherwise, you suffer the Curse Cube Penalty as normal.",
    },
    {
      id: "critical-movements",
      name: "Critical Movements",
      effect: "Weapon Attack you make gain KEEN.",
    },
    {
      id: "dour",
      name: "Dour",
      effect:
        "If no ally is adjacent to you, your Weapon Attack gain a bonus of +2 to HIT and your Spell Attack gain a bonus of +1 DMG.",
    },
    {
      id: "dragon-s-breath",
      name: "Dragon's Breath",
      effect:
        "Whenever you take a Recall Action, you belch fire breath, taking an additional Curse Cube (to a total of two) and choosing an area (blue square) within Range 1 to inflict BURN 4 on each Character in it. Each of the other Heroes who was not caught by the fire finds this hilarious, and receives an INSPIRATION token.",
    },
    {
      id: "fainted-memoir",
      name: "Fainted Memoir",
      effect: "Whenever a Hero takes a Recall Action, they gain an INSPIRATION token and receive EMPOWER.",
    },
    {
      id: "fighting-back",
      name: "Fighting Back",
      effect:
        "Whenever any Hero takes an Interruption or a Reaction to respond to an attack, the attacker takes 1 non-preventable damage.",
    },
    {
      id: "fighting-spirit",
      name: "Fighting Spirit",
      effect: "Whenever a Monster is killed: Self, Regain 1 Health",
    },
    {
      id: "gold-digger",
      name: "Gold Digger",
      effect:
        "Whenever you search a Chest or grab a Loot, you draw the top two cards of the Chest deck, choose one of them to keep, and discard the other instead of just drawing the top card.",
    },
    {
      id: "heroic-resolution",
      name: "Heroic Resolution",
      effect:
        "Whenever a Hero would be Knocked Out by an attack's damage, they may make a Strength (yellow) Skill Challenge of difficulty 13. Each Melee cube they have gives them a +2 bonus to their roll. If they succeed, they drop to 1 Health instead. If they fail, they are Knocked Out as normal.",
    },
    {
      id: "hurry-up",
      name: "Hurry Up",
      effect:
        "Whenever any Hero Expends 1 AC to take an Additional Move Action on a turn, that Additional Move Action gains +1 MOVEMENT and TRAMPLE 2.",
    },
    {
      id: "inspired",
      name: "Inspired",
      effect:
        "Once per turn and only during your turn, you may reroll a d20 you just rolled if you disliked the result.",
    },
    {
      id: "inspiring-presence",
      name: "Inspiring Presence",
      effect: "Weapon Attack made by any Hero within Range 1 of them gain a +1 TO HIT Bonus.",
    },
    {
      id: "kitten-chaser",
      name: "Kitten Chaser",
      effect:
        "Whenever you Expend 1 AC to take an additional Move Action (this does not include any Agility Skills or your Free Move Action), you gain FOCUS 2.",
    },
    {
      id: "lone-wolf",
      name: "Lone Wolf",
      effect:
        "While no other ally is adjacent to you (Heroes, Comrades, and Pets are allies), whenever you take an Interrupt or a Reaction against an attack or threat generated by a Monster, the attacking monster takes 2 non-preventable DMG.",
    },
    {
      id: "moves-like-jagger",
      name: "Moves Like Jagger",
      effect: "Whenever you take a Reaction also Target Other Hero, INSPIRE.",
    },
    {
      id: "obscure-lore",
      name: "Obscure Lore",
      effect: "FOCUS effects you cast gain a +1 Bonus.",
    },
    {
      id: "prohibition",
      name: "Prohibition",
      effect:
        "Each Hero can, once per turn, take a Curse Cube to reroll a d20 they just rolled and disliked the result.",
    },
    {
      id: "protector",
      name: "Protector",
      effect: "PREVENT effects any Hero casts gain a +1 BONUS.",
    },
    {
      id: "reckless-revenge",
      name: "Reckless Revenge",
      effect: "Whenever you lose 1 or more Health, you gain FOCUS 1 (suffering damage causes loss of life).",
    },
    {
      id: "sentinel",
      name: "Sentinel",
      effect:
        "Whenever an ally Character adjacent to you is attacked, as an Interrupt, you may Expend 1 Action Cube to make a Weapon Attack of +0 HIT against the Monster attacking them, if that Monster is also in your weapon's Range. If that Monster is defeated by your attack, cancel its current attack: It won't cause damage to any of its targets. NOTE: If you take an Interrupt against a Monster's attack, you cannot also take Reactions against any threats generated by this same attack.",
    },
    {
      id: "setting-sun-s-blessing",
      name: "Setting Sun's Blessing",
      effect:
        "Heroes hit with Weapon Attack and succeed with Skill Challenges whenever they roll 1 on the d20. Also, whenever a Hero casts a Spell Attack effect, they must roll the d20: if they roll 16+, that Spell Attack is a Critical Hit (it deals double the damage it normally would).",
    },
    {
      id: "sisters-bond",
      name: "Sisters Bond",
      effect:
        "Whenever other Hero within Range 1 would suffer damage or receive a Curse Cube, you may suffer that damage or receive that Curse Cube on their place. If you do, you feel rewarded and gain an INSPIRATION token.",
    },
    {
      id: "taunt",
      name: "Taunt",
      effect:
        "Whenever your allies in Range 1 are attacked, you may suffer FATIGUE 1 to: COVER target ALLY (if two or more allies are being attacked at the same time, you can Cover only one of them). Covering a Target like this takes no action and is done at Interrupt speed, but is not considered an Interrupt.",
    },
    {
      id: "throat-slitter",
      name: "Throat Slitter",
      effect: "Whenever you deliver a Killing Blow: you gain FOCUS 1. This effect can trigger only once per turn.",
    },
    {
      id: "truthful",
      name: "Truthful",
      effect: "You take only one Curse Cube when taking Recall Actions.",
    },
    {
      id: "uncertain-readings",
      name: "Uncertain Readings",
      effect:
        "Heroes can take a Curse Cube and suffer BRITTLE to turn an Accuracy Check they just missed into a success.",
    },
    {
      id: "valorous-party",
      name: "Valorous Party",
      effect: "Whenever a Hero scores a Critical Hit, that Hero may gain their choice of FOCUS 1 or CLEANSE 1",
    },
    {
      id: "vision-beyond-reach",
      name: "Vision Beyond Reach",
      effect:
        "All Ranged Weapon Attack you make and Ranged effects you cast gain +1 RANGE. Then, you may continue to play the Adventure",
    },
  ];

  public find(auraId: string): Aura | undefined {
    return _.find(this.auras, { id: auraId });
  }

  public findAll(): Aura[] {
    return this.auras;
  }
}
